ARG BASE_IMAGE
FROM ${BASE_IMAGE}
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends systemd systemd-sysv dbus ca-certificates curl python3 procps util-linux && apt-get clean
ENV container=podman
STOPSIGNAL SIGRTMIN+3
CMD ["/sbin/init"]
