if(APPLE)
  set(BLAH2_GPU_DEFAULT "OFF")
else()
  set(BLAH2_GPU_DEFAULT "AUTO")
endif()
set(BLAH2_GPU "${BLAH2_GPU_DEFAULT}" CACHE STRING "Build GPU module: AUTO, ON or OFF")
set_property(CACHE BLAH2_GPU PROPERTY STRINGS AUTO ON OFF)
set(VKFFT_ROOT "" CACHE PATH "VkFFT 1.3.4 source directory")
add_library(blah2GpuProcess STATIC ${PROJECT_ROOT}/src/process/ambiguity/GpuProcess.cpp)
target_compile_features(blah2GpuProcess PUBLIC cxx_std_17)
target_link_libraries(blah2GpuProcess PUBLIC Threads::Threads)
if(TARGET blah2)
  target_link_libraries(blah2 PRIVATE blah2GpuProcess)
endif()
if(NOT BLAH2_GPU MATCHES "^(AUTO|ON|OFF)$")
  message(FATAL_ERROR "BLAH2_GPU must be AUTO, ON or OFF")
endif()
if(NOT BLAH2_GPU STREQUAL "OFF")
  find_package(Vulkan QUIET)
  find_package(glslang CONFIG QUIET)
  # Ubuntu 22.04 ships exported targets without a glslangConfig.cmake.
  if(NOT TARGET glslang::glslang)
    find_path(GLSLANG_LEGACY_CMAKE glslangTargets.cmake
      PATHS /usr/lib/${CMAKE_LIBRARY_ARCHITECTURE}/cmake /usr/lib64/cmake /usr/lib/cmake)
    if(GLSLANG_LEGACY_CMAKE)
      foreach(lib IN ITEMS OSDependent OGLCompiler HLSL glslang SPIRV glslang-default-resource-limits)
        include(${GLSLANG_LEGACY_CMAKE}/${lib}Targets.cmake)
        if(TARGET ${lib} AND NOT TARGET glslang::${lib})
          add_library(glslang::${lib} ALIAS ${lib})
        endif()
      endforeach()
    endif()
  endif()
  if(Vulkan_FOUND AND TARGET glslang::glslang AND EXISTS "${VKFFT_ROOT}/vkFFT/vkFFT.h")
    add_library(blah2GpuVulkan MODULE ${PROJECT_ROOT}/src/process/ambiguity/VulkanBackend.cpp)
    target_compile_features(blah2GpuVulkan PRIVATE cxx_std_17)
    target_compile_definitions(blah2GpuVulkan PRIVATE VKFFT_BACKEND=0)
    target_include_directories(blah2GpuVulkan SYSTEM PRIVATE
      ${VKFFT_ROOT}/vkFFT ${Vulkan_INCLUDE_DIRS})
    # VkFFT includes glslang_c_interface.h without its parent path.
    find_path(GLSLANG_C_INCLUDE glslang_c_interface.h PATH_SUFFIXES glslang/Include REQUIRED)
    target_include_directories(blah2GpuVulkan SYSTEM PRIVATE ${GLSLANG_C_INCLUDE})
    target_link_libraries(blah2GpuVulkan PRIVATE Vulkan::Vulkan glslang::glslang
      glslang::SPIRV glslang::glslang-default-resource-limits)
    if(APPLE)
      # FP64 chirp tables are setup constants; all frame FFTs remain on the GPU.
      target_link_libraries(blah2GpuVulkan PRIVATE ${BLAH2_FFTW3_LIBRARY})
    endif()
    # Vulkan's zero-initialized structs intentionally initialize sType first.
    target_compile_options(blah2GpuVulkan PRIVATE -Wno-missing-field-initializers)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      # This versioned C++ plugin ABI uses unmangled names for dlsym; these
      # exports are never called from C. Keep the stable names under -Werror.
      target_compile_options(blah2GpuVulkan PRIVATE -Wno-return-type-c-linkage)
    endif()
    set_target_properties(blah2GpuVulkan PROPERTIES PREFIX "" OUTPUT_NAME "blah2-gpu-vulkan"
      LIBRARY_OUTPUT_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
    if(TARGET blah2)
      add_dependencies(blah2 blah2GpuVulkan)
    endif()
    add_executable(blah2GpuWorker ${PROJECT_ROOT}/src/process/ambiguity/GpuWorker.cpp)
    target_link_libraries(blah2GpuWorker PRIVATE blah2GpuProcess ${CMAKE_DL_LIBS})
    set_target_properties(blah2GpuWorker PROPERTIES OUTPUT_NAME "blah2-gpu-worker")
    add_dependencies(blah2GpuWorker blah2GpuVulkan)
    if(TARGET blah2)
      add_dependencies(blah2 blah2GpuWorker)
    endif()
    message(STATUS "GPU acceleration: portable Vulkan module enabled")
  elseif(BLAH2_GPU STREQUAL "ON")
    message(FATAL_ERROR "GPU build needs Vulkan/glslang development packages and VKFFT_ROOT (VkFFT 1.3.4)")
  else()
    message(STATUS "GPU dependencies absent: building CPU fallback (BLAH2_GPU=ON requires GPU support)")
  endif()
endif()
